CREATE DATABASE Bank;

CREATE TABLE Ort (
PLZ INT PRIMARY KEY,
Ortsname VARCHAR(45) NOT NULL,
Bundesland VARCHAR(20)

);

CREATE TABLE Kunde (
KundenID INT PRIMARY KEY IDENTITY(1,1),
Vorname VARCHAR(255) NOT NULL,
Nachname VARCHAR(255) NOT NULL,
Tele VARCHAR(12),
Mail VARCHAR(255) NOT NULL,
PLZ INT FOREIGN KEY (PLZ) REFERENCES Ort(PLZ)
);

CREATE TABLE Bank (
KontoID INT PRIMARY KEY IDENTITY(1,1),
IBAN VARCHAR(20) NOT NULL,
BIC VARCHAR(11) NOT NULL,
Kontostand DECIMAL(15,2) CHECK (Kontostand >= 0) NOT NULL,
KundenID INT NOT NULL,
FOREIGN KEY (KundenID) REFERENCES Kunde(KundenID)
);
